# Generated by Django 4.2.3 on 2023-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='skills',
            name='exp',
        ),
    ]
